### ISSUE TITLE
Enhance metrics collection for different Redis Data Types commands

### ISSUE THREAD

**Issue by kesseract** [Redislabs-Solution-Architects/ecstats2#11]
We have a list of different Redis Data Type commands in AWS ElastiCache Metrics: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/CacheMetrics.Redis.html

Please verify if we are capturing all.

**Comment by thomasefthymiou78** [comment]
Actions
-------
- Implement missing EC ClusterBasedCmds, EvalBasedCmds, GeoSpatialBasedCmds, PubSubBasedCmds
- EC is not providing BitmapBasedCmds
- Fix ordering of the metrics to match cloudwatch metrics
- Update commands in OSStats script to match the stats of ECstats
